### ISSUE TITLE
Remove "revoke file" page

### ISSUE THREAD

**Issue by tarneaux** [bain3/f.bain#12]
# Description
I am unable to revoke a file on the revocation page with the error "Unauthorized: bad revocation key & ID combination".

![image](https://github.com/bain3/f.bain/assets/62650051/6e2a2652-a98f-45dd-89a8-7f795099ea4b)
(no risk with the tokens, it's a test file which has also been deleted)

# Steps to reproduce

- Upload a file.
- Copy the URL after it was sent.
- Paste it into the revocation page.
- Click "revoke".

# Additional information

Browser: [QuteBrowser](https://qutebrowser.org/)

Host: https://files.renn.es

Web server and reverse proxy: caddy

**Comment by bain3** [comment]
Hi,
you can revoke the file directly on the files download page by clicking the cog icon. This page should actually be completely removed.
