### ISSUE TITLE
Avoid using characters not commonly found in URLs

### ISSUE THREAD

**Issue by tarneaux** [bain3/f.bain#19]
Whenever I send a file through f.bain, a parenthesis can appear in the token, which makes the link highlight only partially in many messaging apps (e.g. Signal).

I think it would be good to remove parentheses and other unusual characters from the allowed token chars, for accessibility but at a small token strength cost.

**Comment by bain3** [comment]
Yeah, thought about that too.
Working out the maths it should actually be only about ~4% less bits of entropy per char if we only kept `[0-9a-zA-Z]`. A single character added to the key and id is sufficient to make up that difference.
